name: db_insertion_test
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  drift: ^2.3.0
  isar: ^3.0.5
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^2.3.2
  isar_generator: ^3.0.5
  lints: ^2.0.1
  test: ^1.22.0
